// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgMQV8lGG2lVNdP1O1m3cKGw2RuH2_vjs',
    appId: '1:343535721195:web:09259b4c3fdc9bcc6a7cae',
    messagingSenderId: '343535721195',
    projectId: 'stock-math-final',
    authDomain: 'stock-math-final.firebaseapp.com',
    storageBucket: 'stock-math-final.appspot.com',
    measurementId: 'G-RMJX3KJGV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCowSFKZ6QktutUoVBCFjZawESoMF6jKCI',
    appId: '1:343535721195:android:ab5ab107c95d44a76a7cae',
    messagingSenderId: '343535721195',
    projectId: 'stock-math-final',
    storageBucket: 'stock-math-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGX7k2bpZYhk3gRvkOrOYDSWfocUTyy-Y',
    appId: '1:343535721195:ios:1a085eec6660a4d96a7cae',
    messagingSenderId: '343535721195',
    projectId: 'stock-math-final',
    storageBucket: 'stock-math-final.appspot.com',
    iosBundleId: 'com.example.stockMathFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGX7k2bpZYhk3gRvkOrOYDSWfocUTyy-Y',
    appId: '1:343535721195:ios:1a085eec6660a4d96a7cae',
    messagingSenderId: '343535721195',
    projectId: 'stock-math-final',
    storageBucket: 'stock-math-final.appspot.com',
    iosBundleId: 'com.example.stockMathFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgMQV8lGG2lVNdP1O1m3cKGw2RuH2_vjs',
    appId: '1:343535721195:web:140d81155ea844106a7cae',
    messagingSenderId: '343535721195',
    projectId: 'stock-math-final',
    authDomain: 'stock-math-final.firebaseapp.com',
    storageBucket: 'stock-math-final.appspot.com',
    measurementId: 'G-1NTHSG017P',
  );
}
